name: "Clean up space"
description: "Clean up disk space on GitHub Runner"
runs:
  using: 'composite'
  steps:
    - name: Display available disk space
      shell: bash
      run: |
        echo "::group::Display disk space"
        sudo df -h
        who
        sudo cat /etc/passwd
        echo "::endgroup::"

    - name: Clean cache
      shell: bash
      run: |
        echo "::group::Clean cache"
        npm cache clean --force
        yarn cache clean
        pip cache purge
        docker system prune -a -f
        echo "::endgroup::"

    - name: Uninstall Homebrew
      shell: bash
      run: |
        curl -fsSL -O https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh
        chmod +x uninstall.sh
        ./uninstall.sh --force

    - name: Remove packages
      shell: bash
      run: |
        echo "::group::Run apt-get remove"
        sudo apt-get remove -y --fix-missing \
            'php.*' \
            '^aspnetcore-.*' \
            '^dotnet-.*' \
            '^llvm-.*' \
            '^mongodb-.*' \
            '^mysql-.*' \
            google-chrome-stable \
            microsoft-edge-stable \
            firefox \
            powershell \
            mono-devel \
            azure-cli \
            google-cloud-sdk \
            google-cloud-cli \
            libgl1-mesa-dri \
            snapd
        sudo apt-get autoremove --purge -y
        sudo apt-get clean
        sudo apt list --installed
        echo "::endgroup::"

    - name: Remove files
      shell: bash
      run: |
        echo "::group::Run rm -rf"
        rm -rf ~/.cache
        sudo rm -rf /root/.cache
        sudo rm -rf /root/.sbt
        sudo rm -rf /tmp/*

        sudo rm -rf /usr/lib/jvm
        sudo rm -rf /usr/lib/heroku
        sudo rm -rf /usr/lib/google-cloud-sdk

        sudo rm -rf /usr/local/.ghcup
        sudo rm -rf /usr/local/julia*
        sudo rm -rf /usr/local/aws-cli
        sudo rm -rf /usr/local/aws-sam-cli
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /usr/local/lib/node_modules
        sudo rm -rf /usr/local/share/powershell
        sudo rm -rf /usr/local/share/chromium

        sudo rm -rf /usr/share/swift
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/share/miniconda
        sudo rm -rf /usr/share/az*
        sudo rm -rf /usr/share/gradle*
        sudo rm -rf /usr/share/sbt
        sudo rm -rf /usr/share/kotlinc
        sudo rm -rf /usr/share/doc

        sudo rm -rf /opt/hostedtoolcache
        sudo rm -rf /opt/az
        sudo rm -rf /opt/microsoft
        sudo rm -rf /opt/google
        sudo rm -rf /opt/pipx
        echo "::endgroup::"

    - name: Display available disk space
      shell: bash
      run: |
        echo "::group::Display disk space"
        sudo df -h
        sudo du -h -d 1 /usr | sort -hr
        sudo du -h -d 1 /opt | sort -hr
        sudo du -h -d 1 /home | sort -hr
        sudo du -h -d 1 /usr/bin | sort -hr
        sudo du -h -d 1 /usr/lib | sort -hr
        sudo du -h -d 1 /usr/local | sort -hr
        sudo du -h -d 1 /usr/share | sort -hr

        sudo du -h -d 1 /var | sort -hr
        sudo du -h -d 1 /etc | sort -hr
        echo "::endgroup::"
