name: Upload Docker images

permissions:
  packages: write      

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-cann:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          docker build -t ascendai/cann:910b-ubuntu2004 -f ./cann/Dockerfile.ubuntu .
          docker build -t ascendai/pytorch:910b-ubuntu2004 -f ./pytorch/Dockerfile.ubuntu .
          cd llm
          docker build -t ascendai/llm:910b-ubuntu2004 -f ./Dockerfile.ubuntu .
 
      - name: Push
        if: github.event_name == 'push'
        run: |
          docker push ascendai/cann:910b-ubuntu2004
          docker push ascendai/pytorch:910b-ubuntu2004
          docker push ascendai/llm:910b-ubuntu2004
