name: Build Docker images (openEuler)

permissions:
  packages: write      

on:
  pull_request:
    paths:
      - 'cann/Dockerfile.openeuler'
      - 'llm/**'
      - 'pytorch/**'
    branches:
      - main
  push:
    paths:
      - 'cann/Dockerfile.openeuler'
      - 'llm/**'
      - 'pytorch/**'
    branches:
      - main

jobs:
  build-cann:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          docker build -t ascendai/cann:910b-openeuler2203sp2 -f ./cann/Dockerfile.openeuler .
          docker build -t ascendai/pytorch:910b-openeuler2203sp2 -f ./pytorch/Dockerfile --build-arg BASE_IMAGE=ascendai/cann:910b-openeuler2203sp2 .
          cd llm
          docker build -t ascendai/llm:910b-openeuler2203sp2 -f ./Dockerfile --build-arg BASE_IMAGE=ascendai/pytorch:910b-openeuler2203sp2 .
 
      - name: Push
        if: github.event_name == 'push'
        run: |
          docker push ascendai/cann:910b-openeuler2203sp2
          docker push ascendai/pytorch:910b-openeuler2203sp2
          docker push ascendai/llm:910b-openeuler2203sp2
